name: qemu
version: 0.1-0
summary: Manages qemu virtual machines
description: |
  Launches qemu virtual machines using kvm script

grade: devel
confinement: strict

apps:
  kvm:
    command: bin/kvm-launcher
    plugs: [home, kvm, network-bind, x11]

parts:
  kvm:
    plugin: dump
    source: bin
    organize:
      kvm-launcher: bin/kvm-launcher
    stage-packages:
      - qemu-kvm
  snappypreload:
    plugin: cmake
    source: snappypreload
    build-packages:
      - build-essential

